//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGalleryProcessor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} - Galleries")]
        public string Feed_TitleFormat {
            get {
                return ((string)(this["Feed_TitleFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Galleries on {0}")]
        public string Feed_DescriptionFormat {
            get {
                return ((string)(this["Feed_DescriptionFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}Galleries")]
        public string Feed_IdFormat {
            get {
                return ((string)(this["Feed_IdFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OriginalImages")]
        public string Folders_OringinalImages {
            get {
                return ((string)(this["Folders_OringinalImages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ScaledImages")]
        public string Folders_ScaledImages {
            get {
                return ((string)(this["Folders_ScaledImages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thumbs")]
        public string Folders_Thumbs {
            get {
                return ((string)(this["Folders_Thumbs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}-LQ.zip")]
        public string Zip_FileNameFormat_LowQuality {
            get {
                return ((string)(this["Zip_FileNameFormat_LowQuality"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}-HQ.zip")]
        public string Zip_FileNameFormat_HighQuality {
            get {
                return ((string)(this["Zip_FileNameFormat_HighQuality"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GalleryData{0}.xml")]
        public string File_GalleryDataFileNameFormat {
            get {
                return ((string)(this["File_GalleryDataFileNameFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GalleryCover.jpg")]
        public string File_GalleryCoverFileName {
            get {
                return ((string)(this["File_GalleryCoverFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/Galleries/{1}/")]
        public string Http_GalleryHttpPathFormat {
            get {
                return ((string)(this["Http_GalleryHttpPathFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/Galleries/")]
        public string Http_GalleriesIndexHttpPathFormat {
            get {
                return ((string)(this["Http_GalleriesIndexHttpPathFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.jpg")]
        public string Image_FileTypeFilter {
            get {
                return ((string)(this["Image_FileTypeFilter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MaxDimensions")]
        public global::WebGalleryProcessor.ScaleMode ImageProcess_Default_ScaledImageScaleMode {
            get {
                return ((global::WebGalleryProcessor.ScaleMode)(this["ImageProcess_Default_ScaledImageScaleMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int ImageProcess_Default_ScaledImageWidth {
            get {
                return ((int)(this["ImageProcess_Default_ScaledImageWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int ImageProcess_Default_ScaledImageHeight {
            get {
                return ((int)(this["ImageProcess_Default_ScaledImageHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FixedHeight")]
        public global::WebGalleryProcessor.ScaleMode ImageProcess_Default_ThumbScaleMode {
            get {
                return ((global::WebGalleryProcessor.ScaleMode)(this["ImageProcess_Default_ThumbScaleMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ImageProcess_Default_ThumbWidth {
            get {
                return ((int)(this["ImageProcess_Default_ThumbWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ImageProcess_Default_ThumbHeight {
            get {
                return ((int)(this["ImageProcess_Default_ThumbHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int CoverRender_Default_ImageRotationMax {
            get {
                return ((int)(this["CoverRender_Default_ImageRotationMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-20")]
        public int CoverRender_Default_ImageRotationMin {
            get {
                return ((int)(this["CoverRender_Default_ImageRotationMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int CoverRender_Default_TitleRotationMax {
            get {
                return ((int)(this["CoverRender_Default_TitleRotationMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public int CoverRender_Default_TitleRotationMin {
            get {
                return ((int)(this["CoverRender_Default_TitleRotationMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CoverRender_Default_TitleOffsetXMin {
            get {
                return ((int)(this["CoverRender_Default_TitleOffsetXMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CoverRender_Default_TitleOffsetXMax {
            get {
                return ((int)(this["CoverRender_Default_TitleOffsetXMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-20")]
        public int CoverRender_Default_TitleOffsetYMin {
            get {
                return ((int)(this["CoverRender_Default_TitleOffsetYMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10")]
        public int CoverRender_Default_TitleOffsetYMax {
            get {
                return ((int)(this["CoverRender_Default_TitleOffsetYMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CoverRender_Default_ImageOffsetXMin {
            get {
                return ((int)(this["CoverRender_Default_ImageOffsetXMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CoverRender_Default_ImageOffsetXMax {
            get {
                return ((int)(this["CoverRender_Default_ImageOffsetXMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CoverRender_Default_ImageOffsetYMin {
            get {
                return ((int)(this["CoverRender_Default_ImageOffsetYMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CoverRender_Default_ImageOffsetYMax {
            get {
                return ((int)(this["CoverRender_Default_ImageOffsetYMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/Galleries#{1}")]
        public string Http_GalleryHttpEnhancedPathFormat {
            get {
                return ((string)(this["Http_GalleryHttpEnhancedPathFormat"]));
            }
        }
    }
}
